name: Radar Przetargi

on:
  workflow_dispatch:

jobs:
  radar:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalacja bibliotek
        run: |
          pip install -r requirements.txt

      - name: Uruchom Radar
        run: |
          python radar.py
